# This is a basic workflow to help you get started with Actions

name: master to pypi with comments


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  FOLDER_WITH_VERSION: scipioninstaller
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        #python setup.py sdist
        echo "${{ secrets.PYPI_COMMENT }}"
        # twine upload dist/* -c "${{ secrets.PYPI_COMMENT }}"
    - name: Get version
      run: |
        printenv
        python -c "import $FOLDER_WITH_VERSION; print('::set_env name=$FOLDER_WITH_VERSION::v'+$FOLDER_WITH_VERSION.__version__);"
        #echo "Version ${{ secrets.FOLDER_WITH_VERSION }} detected"
    - name: Tag commit
      run: |
        printenv
        #git tag $PACKAGE_VERSION
    - name: Push tag
      run: |
        #git push $PACKAGE_VERSION